# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: "1 - [FEAT] Build"

on:
  workflow_dispatch:    
  push:
    branches:
      - main
      - "feature**"
  pull_request:
    branches:
      - main
      - "feature**"

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATHS: |
    ./src/Post.Command.Api/Post.Command.Api.csproj
    ./src/Post.Query.Api/Post.Query.Api.csproj

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore and Build Projects
      run: |
        for PROJECT in ${{ env.PROJECT_PATHS }}; do
          echo "Restoring packages for $PROJECT"
          dotnet restore $PROJECT
          echo "Building $PROJECT"
          dotnet build $PROJECT -c Release --no-restore
        done

